version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.9
  - dependency-name: "@types/mongodb"
    versions:
    - 3.6.10
    - 3.6.11
    - 3.6.3
    - 3.6.5
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: "@octokit/rest"
    versions:
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: "@types/unzipper"
    versions:
    - 0.10.3
  - dependency-name: source-map-support
    versions:
    - 0.5.19
  - dependency-name: "@actions/core"
    versions:
    - 1.2.6
  - dependency-name: bl
    versions:
    - 2.2.1
